{
  imports = [
    # ./chromium.nix
    ./btop.nix
    ./direnv.nix
    ./discord.nix
    ./eza.nix
    ./fastfetch.nix
    ./fish.nix
    ./fzf.nix
    ./gh-dash.nix
    ./ghostty
    ./git.nix
    ./helium.nix
    ./hyprland
    ./lazydocker.nix
    ./lazygit.nix
    ./neovide.nix
    ./neovim.nix
    ./opencode
    ./services
    ./starship.nix
    ./stylix.nix
    ./thunderbird
    ./tmux.nix
    ./walker
    ./waybar
    ./wlogout
    ./xdg-pwas.nix
    ./zoxide.nix
  ];
}
