{
  pkgs,
  lib,
  config,
  ...
}: let
  inherit (config.suckless) colors font;

  # #rrggbb -> 0xrrggbbff for dwl's colour tables.
  toBar = hex: "0x" + lib.toLower (lib.removePrefix "#" hex) + "ff";

  ocr-copy = pkgs.callPackage ../../pkgs/ocr-copy.nix {};

  foot = "${pkgs.foot}/bin/foot";
  wmenuRun = "${pkgs.wmenu}/bin/wmenu-run";
  wmenu = "${pkgs.wmenu}/bin/wmenu";
  grimblast = "${pkgs.grimblast}/bin/grimblast";
  cliphist = "${pkgs.cliphist}/bin/cliphist";
  wlCopy = "${pkgs.wl-clipboard}/bin/wl-copy";
  wpctl = "${pkgs.wireplumber}/bin/wpctl";
  brightnessctl = "${pkgs.brightnessctl}/bin/brightnessctl";
  playerctl = "${pkgs.playerctl}/bin/playerctl";

  # A complete config.h. We own the whole file rather than patching dwl's
  # default in place: the keybinds mirror the maximal hyprland session
  # (home-manager/profiles/maximal/hyprland/hyprland/binds.nix) as closely as
  # dwl's dwm-style model allows. Where hyprland's directional focus/move has no
  # dwl equivalent we fall back to dwl-native stack controls, and binds for apps
  # absent from the lean profile (thunar, walker, wleave) are dropped.
  configH = pkgs.writeText "dwl-config.h" ''
    /* Generated by home-manager (profiles/suckless/dwl.nix) -- do not edit. */

    /* Taken from https://github.com/djpohly/dwl/issues/466 */
    #define COLOR(hex)    { ((hex >> 24) & 0xFF) / 255.0f, \
                            ((hex >> 16) & 0xFF) / 255.0f, \
                            ((hex >> 8) & 0xFF) / 255.0f, \
                            (hex & 0xFF) / 255.0f }

    /* appearance */
    static const int sloppyfocus               = 1;  /* focus follows mouse */
    static const int bypass_surface_visibility = 0;
    static const unsigned int borderpx         = 1;  /* border pixel of windows */
    static const int showbar                   = 1;  /* 0 means no bar */
    static const int topbar                    = 1;  /* 0 means bottom bar */
    static const char *fonts[]                 = {"${font.name}:size=10"};
    static const float rootcolor[]             = COLOR(${toBar colors.base00});
    /* Set the alpha to zero to restore the old (pre xdg-protocol) behaviour. */
    static const float fullscreen_bg[]         = {0.0f, 0.0f, 0.0f, 1.0f};

    /* base16 colours: foreground, background, border */
    static uint32_t colors[][3] = {
      [SchemeNorm] = { ${toBar colors.base05}, ${toBar colors.base00}, ${toBar colors.base02} },
      [SchemeSel]  = { ${toBar colors.base00}, ${toBar colors.base0D}, ${toBar colors.base0D} },
      [SchemeUrg]  = { ${toBar colors.base00}, ${toBar colors.base08}, ${toBar colors.base08} },
    };

    /* tagging */
    static char *tags[] = { "1", "2", "3", "4", "5", "6", "7", "8", "9" };

    /* logging */
    static int log_level = WLR_ERROR;

    static const Rule rules[] = {
      /* app_id  title  tags mask  isfloating  monitor */
      { NULL,    NULL,  0,         0,          -1 }, /* at least one rule must exist */
    };

    /* layout(s) */
    static const Layout layouts[] = {
      /* symbol  arrange function */
      { "[]=",   tile },
      { "><>",   NULL },    /* no layout function means floating behavior */
      { "[M]",   monocle },
    };

    /* monitors: runtime layout is applied by dwl-monitors (./monitors.nix) */
    static const MonitorRule monrules[] = {
      /* name  mfact  nmaster  scale  layout       rotate/reflect              x   y */
      { NULL,  0.55f, 1,       1,     &layouts[0], WL_OUTPUT_TRANSFORM_NORMAL, -1, -1 },
    };

    /* keyboard */
    static const struct xkb_rule_names xkb_rules = {
      .options = NULL,
    };

    static const int repeat_rate  = 25;
    static const int repeat_delay = 600;

    /* Trackpad */
    static const int tap_to_click            = 1;
    static const int tap_and_drag            = 1;
    static const int drag_lock               = 1;
    static const int natural_scrolling       = 0;
    static const int disable_while_typing    = 1;
    static const int left_handed             = 0;
    static const int middle_button_emulation = 0;
    static const enum libinput_config_scroll_method scroll_method = LIBINPUT_CONFIG_SCROLL_2FG;
    static const enum libinput_config_click_method click_method = LIBINPUT_CONFIG_CLICK_METHOD_BUTTON_AREAS;
    static const uint32_t send_events_mode = LIBINPUT_CONFIG_SEND_EVENTS_ENABLED;
    static const enum libinput_config_accel_profile accel_profile = LIBINPUT_CONFIG_ACCEL_PROFILE_ADAPTIVE;
    static const double accel_speed = 0.0;
    static const enum libinput_config_tap_button_map button_map = LIBINPUT_CONFIG_TAP_MAP_LRM;

    /* Use the Super/Windows key as the modifier (mirrors the hyprland session). */
    #define MODKEY WLR_MODIFIER_LOGO

    #define TAGKEYS(KEY,SKEY,TAG) \
      { MODKEY,                    KEY,  view,       {.ui = 1 << TAG} }, \
      { MODKEY|WLR_MODIFIER_CTRL,  KEY,  toggleview, {.ui = 1 << TAG} }, \
      { MODKEY|WLR_MODIFIER_SHIFT, SKEY, tag,        {.ui = 1 << TAG} }, \
      { MODKEY|WLR_MODIFIER_CTRL|WLR_MODIFIER_SHIFT, SKEY, toggletag, {.ui = 1 << TAG} }

    /* helper for spawning shell commands in the pre dwm-5.0 fashion */
    #define SHCMD(cmd) { .v = (const char*[]){ "/bin/sh", "-c", cmd, NULL } }

    /* commands (absolute store paths; keysyms are matched case-insensitively) */
    static const char *termcmd[]      = { "${foot}", NULL };
    static const char *menucmd[] = {
      "${wmenuRun}",
      "-f", "${font.name} 10",
      "-N", "${colors.base00}",
      "-n", "${colors.base05}",
      "-M", "${colors.base00}",
      "-m", "${colors.base0D}",
      "-S", "${colors.base0D}",
      "-s", "${colors.base00}",
      NULL
    };
    static const char *ocrcmd[]       = { "${ocr-copy}/bin/ocr-copy", NULL };
    static const char *shotcmd[]      = { "${grimblast}", "--notify", "--freeze", "copysave", "screen", NULL };
    static const char *areashotcmd[]  = { "${grimblast}", "--notify", "--freeze", "copysave", "area", NULL };
    static const char *volupcmd[]     = { "${wpctl}", "set-volume", "-l", "1", "@DEFAULT_AUDIO_SINK@", "5%+", NULL };
    static const char *voldncmd[]     = { "${wpctl}", "set-volume", "@DEFAULT_AUDIO_SINK@", "5%-", NULL };
    static const char *volmutecmd[]   = { "${wpctl}", "set-mute", "@DEFAULT_AUDIO_SINK@", "toggle", NULL };
    static const char *micmutecmd[]   = { "${wpctl}", "set-mute", "@DEFAULT_AUDIO_SOURCE@", "toggle", NULL };
    static const char *brightupcmd[]  = { "${brightnessctl}", "s", "10%+", NULL };
    static const char *brightdncmd[]  = { "${brightnessctl}", "s", "10%-", NULL };
    static const char *nextcmd[]      = { "${playerctl}", "next", NULL };
    static const char *prevcmd[]      = { "${playerctl}", "previous", NULL };
    static const char *playpausecmd[] = { "${playerctl}", "play-pause", NULL };

    static const Key keys[] = {
      /* --- applications & screenshots (mirror the hyprland binds) --- */
      { MODKEY,                    XKB_KEY_Return, spawn, {.v = termcmd} },     /* super+enter   -> terminal      */
      { MODKEY,                    XKB_KEY_d,      spawn, {.v = menucmd} },     /* super+d       -> launcher      */
      { MODKEY,                    XKB_KEY_c,      spawn, {.v = ocrcmd} },      /* super+c       -> OCR to clip   */
      { MODKEY|WLR_MODIFIER_SHIFT, XKB_KEY_s,      spawn, {.v = shotcmd} },     /* super+shift+s -> shot (screen) */
      { 0,                         XKB_KEY_Print,  spawn, {.v = areashotcmd} }, /* print         -> shot (area)   */
      { MODKEY,                    XKB_KEY_v,      spawn,                       /* super+v       -> clipboard     */
        SHCMD("${cliphist} list | ${wmenu} | ${cliphist} decode | ${wlCopy}") },

      /* --- window & layout management --- */
      { MODKEY,                    XKB_KEY_q,      killclient,       {0} },                /* super+q       -> close      */
      { MODKEY,                    XKB_KEY_f,      togglefloating,   {0} },                /* super+f       -> float      */
      { MODKEY|WLR_MODIFIER_SHIFT, XKB_KEY_f,      togglefullscreen, {0} },                /* super+shift+f -> fullscreen */
      { MODKEY,                    XKB_KEY_b,      togglebar,        {0} },                /* super+b       -> toggle bar */
      { MODKEY,                    XKB_KEY_j,      focusstack,       {.i = +1} },          /* super+j       -> focus next */
      { MODKEY,                    XKB_KEY_k,      focusstack,       {.i = -1} },          /* super+k       -> focus prev */
      { MODKEY,                    XKB_KEY_h,      setmfact,         {.f = -0.05f} },      /* super+h       -> shrink     */
      { MODKEY,                    XKB_KEY_l,      setmfact,         {.f = +0.05f} },      /* super+l       -> grow       */
      { MODKEY,                    XKB_KEY_i,      incnmaster,       {.i = +1} },          /* super+i       -> +master    */
      { MODKEY|WLR_MODIFIER_SHIFT, XKB_KEY_i,      incnmaster,       {.i = -1} },          /* super+shift+i -> -master    */
      { MODKEY|WLR_MODIFIER_SHIFT, XKB_KEY_Return, zoom,             {0} },                /* super+shift+enter -> zoom   */
      { MODKEY,                    XKB_KEY_t,      setlayout,        {.v = &layouts[0]} }, /* super+t       -> tile       */
      { MODKEY,                    XKB_KEY_m,      setlayout,        {.v = &layouts[2]} }, /* super+m       -> monocle    */
      { MODKEY,                    XKB_KEY_space,  setlayout,        {0} },                /* super+space   -> last layout */

      /* --- tags (hyprland workspaces 1-9): super+N view, super+shift+N move --- */
      { MODKEY,                    XKB_KEY_Tab,        view, {0} },        /* super+tab       -> last tag  */
      { MODKEY,                    XKB_KEY_0,          view, {.ui = ~0} }, /* super+0         -> all tags  */
      { MODKEY|WLR_MODIFIER_SHIFT, XKB_KEY_parenright, tag,  {.ui = ~0} }, /* super+shift+0   -> tag all   */
      TAGKEYS(XKB_KEY_1, XKB_KEY_exclam,      0),
      TAGKEYS(XKB_KEY_2, XKB_KEY_at,          1),
      TAGKEYS(XKB_KEY_3, XKB_KEY_numbersign,  2),
      TAGKEYS(XKB_KEY_4, XKB_KEY_dollar,      3),
      TAGKEYS(XKB_KEY_5, XKB_KEY_percent,     4),
      TAGKEYS(XKB_KEY_6, XKB_KEY_asciicircum, 5),
      TAGKEYS(XKB_KEY_7, XKB_KEY_ampersand,   6),
      TAGKEYS(XKB_KEY_8, XKB_KEY_asterisk,    7),
      TAGKEYS(XKB_KEY_9, XKB_KEY_parenleft,   8),

      /* --- multi-monitor (super+shift+h/l send the window across) --- */
      { MODKEY,                    XKB_KEY_comma,  focusmon, {.i = WLR_DIRECTION_LEFT} },
      { MODKEY,                    XKB_KEY_period, focusmon, {.i = WLR_DIRECTION_RIGHT} },
      { MODKEY|WLR_MODIFIER_SHIFT, XKB_KEY_h,      tagmon,   {.i = WLR_DIRECTION_LEFT} },
      { MODKEY|WLR_MODIFIER_SHIFT, XKB_KEY_l,      tagmon,   {.i = WLR_DIRECTION_RIGHT} },

      /* --- media, volume & brightness --- */
      { 0,      XKB_KEY_XF86AudioRaiseVolume, spawn, {.v = volupcmd} },
      { 0,      XKB_KEY_XF86AudioLowerVolume, spawn, {.v = voldncmd} },
      { 0,      XKB_KEY_XF86AudioMute,        spawn, {.v = volmutecmd} },
      { 0,      XKB_KEY_XF86AudioMicMute,     spawn, {.v = micmutecmd} },
      { MODKEY, XKB_KEY_bracketright,         spawn, {.v = brightupcmd} },
      { MODKEY, XKB_KEY_bracketleft,          spawn, {.v = brightdncmd} },
      { 0,      XKB_KEY_XF86AudioNext,        spawn, {.v = nextcmd} },
      { 0,      XKB_KEY_XF86AudioPrev,        spawn, {.v = prevcmd} },
      { 0,      XKB_KEY_XF86AudioPlay,        spawn, {.v = playpausecmd} },
      { 0,      XKB_KEY_XF86AudioPause,       spawn, {.v = playpausecmd} },

      /* --- exit & VT switching --- */
      { MODKEY|WLR_MODIFIER_SHIFT, XKB_KEY_z, quit, {0} }, /* super+shift+z -> exit dwl */
      { WLR_MODIFIER_CTRL|WLR_MODIFIER_ALT, XKB_KEY_Terminate_Server, quit, {0} },
    #define CHVT(n) { WLR_MODIFIER_CTRL|WLR_MODIFIER_ALT, XKB_KEY_XF86Switch_VT_##n, chvt, {.ui = (n)} }
      CHVT(1), CHVT(2), CHVT(3), CHVT(4),  CHVT(5),  CHVT(6),
      CHVT(7), CHVT(8), CHVT(9), CHVT(10), CHVT(11), CHVT(12),
    };

    static const Button buttons[] = {
      { ClkLtSymbol, 0,      BTN_LEFT,   setlayout,      {.v = &layouts[0]} },
      { ClkLtSymbol, 0,      BTN_RIGHT,  setlayout,      {.v = &layouts[2]} },
      { ClkTitle,    0,      BTN_MIDDLE, zoom,           {0} },
      { ClkStatus,   0,      BTN_MIDDLE, spawn,          {.v = termcmd} },
      { ClkClient,   MODKEY, BTN_LEFT,   moveresize,     {.ui = CurMove} },
      { ClkClient,   MODKEY, BTN_MIDDLE, togglefloating, {0} },
      { ClkClient,   MODKEY, BTN_RIGHT,  moveresize,     {.ui = CurResize} },
      { ClkTagBar,   0,      BTN_LEFT,   view,           {0} },
      { ClkTagBar,   0,      BTN_RIGHT,  toggleview,     {0} },
      { ClkTagBar,   MODKEY, BTN_LEFT,   tag,            {0} },
      { ClkTagBar,   MODKEY, BTN_RIGHT,  toggletag,      {0} },
    };
  '';

  # The community "bar" user patch (adds an in-compositor status bar).
  barPatch = pkgs.fetchpatch {
    name = "dwl-bar.patch";
    url = "https://codeberg.org/dwl/dwl-patches/raw/branch/main/patches/bar/bar.patch";
    hash = "sha256-guW5Gan9jg5S8O7F/LfvQpUJy7Cgs8ly89peL7YazeI=";
  };

  dwl-suckless = pkgs.dwl.overrideAttrs (old: {
    patches = (old.patches or []) ++ [barPatch];
    # The bar patch draws text with fcft/pixman and pulls in libdrm headers.
    buildInputs = (old.buildInputs or []) ++ [pkgs.fcft pkgs.libdrm];

    # Drop in our config.h directly; the Makefile only copies config.def.h ->
    # config.h when config.h is absent, so ours wins. The build fails loudly if
    # it ever drifts out of sync with dwl.c.
    postPatch =
      (old.postPatch or "")
      + ''
        cp ${configH} config.h
      '';
  });
in {
  # dwl: the pure Wayland successor to dwm, with the bar patch and a keybind set
  # mirroring the maximal hyprland session. Monitor layout is applied at runtime
  # by the compositor-agnostic `dwl-monitors` (./monitors.nix).
  home.packages = [
    dwl-suckless
    pkgs.wmenu # super+d launcher
    pkgs.grimblast # screenshots (super+shift+s / Print)
    pkgs.wl-clipboard
    ocr-copy # super+c
  ];
}
