{
  imports = [
    ./audio.nix
    ./binfmt.nix
    ./bluetooth.nix
    ./boot.nix
    ./common-packages.nix
    ./docker.nix
    ./env.nix
    ./home-manager.nix
    ./kernel.nix
    ./ly.nix
    ./net.nix
    ./nh.nix
    ./nix.nix
    ./power.nix
    ./qemu.nix
    ./timezone.nix
    ./user.nix
    ./zram.nix
  ];
}
