#!/usr/bin/env bash
# Generate docs/inventory.md from the source tree.
#
#   ./scripts/inventory.sh            write docs/inventory.md
#   ./scripts/inventory.sh --check    exit 1 if docs/inventory.md is stale
#   ./scripts/inventory.sh --stdout   print, write nothing
#
# Every fact here is derived, so prose must never restate one. Aspect names are
# literal everywhere (docs-check.sh asserts it), which is what lets grep stand
# in for an eval.

set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

OUT=docs/inventory.md

render() {
  local files aspects total multi

  files=$(find modules -name '*.nix' ! -path '*/_*' | sort)
  total=0
  multi=0
  while IFS= read -r f; do
    n=$({ grep -ohE 'flake\.modules\.[a-zA-Z]+\.[a-zA-Z0-9_-]+' "$f" || true; } | sort -u | wc -l)
    if [ "$n" -ge 1 ]; then total=$((total + 1)); fi
    if [ "$n" -ge 2 ]; then multi=$((multi + 1)); fi
  done <<<"$files"

  echo "# Inventory"
  echo
  echo "Generated by \`scripts/inventory.sh\`. Do not edit; do not restate any of"
  echo "it in prose. \`scripts/docs-check.sh\` fails when this file is stale."
  echo
  echo "## Hosts"
  echo
  echo "Aspect order is load-bearing — it sets merge order, which reaches"
  echo "derivation hashes."
  echo
  echo "| Host | Aspects |"
  echo "| --- | --- |"
  for h in modules/hosts/*.nix; do
    name=$(basename "$h" .nix)
    case $name in generator | record) continue ;; esac
    list=$(grep -oE 'aspects = \[[^]]*\]' "$h" | sed 's/aspects = \[//; s/\]//; s/"//g; s/  */ /g; s/^ //; s/ $//')
    printf '| `%s` | `%s` |\n' "$name" "$list"
  done
  echo
  echo "## Aspects"
  echo
  echo "Enumerate the files behind any row with"
  echo '`rg -l "flake\.modules\.<class>\.<aspect>" modules/`.'
  echo
  echo "| Aspect | Classes | Files |"
  echo "| --- | --- | --- |"
  while IFS= read -r f; do
    { grep -ohE 'flake\.modules\.[a-zA-Z]+\.[a-zA-Z0-9_-]+' "$f" || true; } | sort -u |
      sed "s|^flake\.modules\.||" | while IFS=. read -r class aspect; do
      echo "$aspect $class"
    done
  done <<<"$files" | LC_ALL=C sort | awk '
    { n[$1]++; if (!seen[$1 " " $2]++) cls[$1] = (cls[$1] == "" ? "" : cls[$1] " ") $2 }
    END { for (a in n) printf "%s\t%s\t%s\n", a, cls[a], n[a] }' |
    LC_ALL=C sort | awk -F'\t' '{ printf "| `%s` | `%s` | %s |\n", $1, $2, $3 }'
  echo
  echo "## Aspect requirements"
  echo
  echo "Declared in the file that creates the dependency, never in a central table."
  echo
  echo "| Aspect | Requires | Declared in |"
  echo "| --- | --- | --- |"
  grep -rn 'aspectRequires\.' modules --include='*.nix' | grep -v 'hosts/generator.nix' | sed 's|^modules/||' |
    while IFS= read -r line; do
      file=${line%%:*}
      body=${line#*:*:}
      a=$(echo "$body" | sed -E 's/.*aspectRequires\.([a-zA-Z0-9_-]+).*/\1/')
      r=$(echo "$body" | grep -oE '\[[^]]*\]' | sed 's/\[//; s/\]//; s/"//g; s/  */ /g; s/^ //; s/ $//')
      printf '| `%s` | `%s` | `%s` |\n' "$a" "$r" "$file"
    done
  echo
  echo "## Counts"
  echo
  echo "| | |"
  echo "| --- | --- |"
  printf '| files declaring at least one aspect | %s |\n' "$total"
  printf '| of those, declaring more than one aspect or class | %s |\n' "$multi"
  printf '| `load-bearing:` pointers | %s |\n' \
    "$(grep -rhc '# load-bearing:' modules --include='*.nix' | awk '{s+=$1} END {print s+0}')"
  printf '| anchors defined in `docs/` | %s |\n' \
    "$(grep -rho '<a id="[^"]*">' docs --include='*.md' | wc -l)"
}

case ${1:-} in
--stdout) render ;;
--check)
  if ! diff -q <(render) "$OUT" >/dev/null 2>&1; then
    echo "$OUT is stale; run ./scripts/inventory.sh" >&2
    diff <(render) "$OUT" | head -20 >&2 || true
    exit 1
  fi
  ;;
*)
  render >"$OUT"
  echo "wrote $OUT"
  ;;
esac
