#!/usr/bin/env bash
# Parse the shell's QML. Nothing in the build does: _config.nix ends in a `cp`,
# so a file that does not parse builds green through all six targets and fails
# only when quickshell starts — after a switch, on the machine, with no bar.
#
#   ./scripts/qml-check.sh            format + lint
#   ./scripts/qml-check.sh format     every .qml matches qmlformat
#   ./scripts/qml-check.sh lint       qmllint, against the built config
#
# Both tools come from the flake's own nixpkgs, never from PATH. A qmlformat
# from a different Qt reformats the whole tree, and a qmllint from a different
# Qt disagrees with the quickshell the shell actually runs under.

set -uo pipefail

cd "$(git rev-parse --show-toplevel)" || exit 2

QML_DIR=modules/quickshell/_qml

nl=$'\n'
export NIX_CONFIG="${NIX_CONFIG:+$NIX_CONFIG$nl}extra-experimental-features = nix-command flakes"

# Flakes only see tracked files.
git add -A >/dev/null 2>&1 || true

bad=0
fail() {
  echo "$1" >&2
  bad=1
}

pin() {
  nix build --no-link --print-out-paths --inputs-from . "nixpkgs#$1" 2>/dev/null
}

QTDECL=$(pin qt6.qtdeclarative)
QUICKSHELL=$(pin quickshell)
if [[ -z $QTDECL || -z $QUICKSHELL ]]; then
  echo "error: could not build qt6.qtdeclarative and quickshell from the pin" >&2
  exit 2
fi
QMLFORMAT=$QTDECL/bin/qmlformat
QMLLINT=$QTDECL/bin/qmllint

# The config derivation, not the source tree: Config.qml is generated, and the
# singleton every other file imports. Linting without it makes all 49 files
# report the same missing import. The host is measured, not written down.
config_attr() {
  nix eval --raw '.#homeConfigurations' --apply \
    'o: let ns = builtins.filter (n: (o.${n}.config.programs.quickshell.enable or false)) (builtins.attrNames o);
        in if ns == [] then "" else builtins.head ns' 2>/dev/null
}

build_config() {
  local who
  who=$(config_attr)
  [[ -n $who ]] || return 1
  nix build --no-link --print-out-paths \
    ".#homeConfigurations.\"$who\".config.programs.quickshell.configs.default" 2>/dev/null
}

CONFIG=$(build_config)
if [[ -z $CONFIG ]]; then
  echo "error: no homeConfiguration enables programs.quickshell" >&2
  exit 2
fi

# 1. Formatting. The tree is qmlformat-clean under default options and stays
#    that way, so a diff is a real deviation rather than a style opinion. Do
#    not add -n: it normalises attribute order and differs on every file.
check_format() {
  local n=0 f
  for f in $(find "$QML_DIR" -name '*.qml' | sort); do
    "$QMLFORMAT" "$f" 2>/dev/null | diff -q - "$f" >/dev/null ||
      { fail "$f: not qmlformat-clean; run  $QMLFORMAT -i $f"; n=$((n + 1)); }
  done
  # Config.qml has no source file to point at. It is generated by a `''` block
  # whose indentation is load-bearing — an interpolation that lands at column 0
  # reindents everything after it, which this catches and nothing else does.
  "$QMLFORMAT" "$CONFIG/Config.qml" 2>/dev/null | diff -q - "$CONFIG/Config.qml" >/dev/null ||
    { fail "modules/quickshell/_config.nix: the generated Config.qml is not qmlformat-clean"; n=$((n + 1)); }
  if [ $n -eq 0 ]; then echo "format: clean"; else echo "format: $n file(s) differ"; fi
}

# 2. Linting. quickshell synthesises a qmldir for the config directory at
#    runtime; qmllint will not, so build one per directory in a temp copy.
#    Nothing may be written into _qml/ — that tree ships wholesale into the
#    user's config, so a stray qmldir or .qmllint.ini moves the store path.
check_lint() {
  local tmp
  tmp=$(mktemp -d -t qml-check-XXXXXX) || return 2
  trap 'rm -rf "$tmp"' RETURN

  mkdir -p "$tmp/qs"
  cp -r --no-preserve=mode "$CONFIG/." "$tmp/qs/" || return 2

  local d rel mod f base
  while IFS= read -r d; do
    rel=${d#"$tmp"/qs}
    rel=${rel#/}
    mod=qs${rel:+.${rel//\//.}}
    {
      echo "module $mod"
      for f in "$d"/*.qml; do
        [ -e "$f" ] || continue
        base=$(basename "$f" .qml)
        # shell.qml is the entry point, not a type; QML types are capitalised.
        case $base in [a-z]*) continue ;; esac
        if head -1 "$f" | grep -q '^pragma Singleton'; then
          echo "singleton $base 1.0 $base.qml"
        else
          echo "$base 1.0 $base.qml"
        fi
      done
    } >"$d/qmldir"
  done < <(find "$tmp/qs" -type d | sort)

  # Four categories are off, all for one reason: quickshell's C++ types are
  # registered imperatively, so its .qmltypes describes them incompletely.
  # Each names the whole of what it currently suppresses, so a reader can tell
  # a tuned gate from an abandoned one. missing-property and unqualified are
  # NOT off — they are the two that catch a mistyped Config role or a name
  # resolved from the wrong scope — so their false positives are suppressed at
  # the two sites that have them instead.
  local off=(
    # PopupAnchor, DBusMenuHandle, UntypedObjectModel, Margins, QList<T*>.
    --unresolved-type disable
    # PanelWindow: quickshell constructs it from C++.
    --uncreatable-type disable
    # fallout from the unresolved PopupAnchor grouped property.
    --missing-type disable
    # QProcess::ExitStatus in Process.onExited.
    --signal-handler-parameters disable
  )

  local out
  out=$("$QMLLINT" "${off[@]}" \
    -I "$tmp" \
    -I "$QTDECL/lib/qt-6/qml" \
    -I "$QUICKSHELL/lib/qt-6/qml" \
    $(find "$tmp/qs" -name '*.qml' | sort) 2>&1)
  local rc=$?

  if [[ $rc -ne 0 || -n $out ]]; then
    # Point at the file a human edits, not at the temp copy.
    echo "$out" | sed "s#$tmp/qs/#$QML_DIR/#g" >&2
    fail "lint: qmllint rejected the shell's QML"
  else
    echo "lint: clean"
  fi
}

case ${1:-all} in
format) check_format ;;
lint) check_lint ;;
all)
  check_format
  check_lint
  ;;
*)
  echo "usage: $0 [format|lint]" >&2
  exit 2
  ;;
esac

exit $bad
