#!/usr/bin/env bash
# Parse the shell's QML. Nothing in the build does: _config.nix ends in a `cp`,
# so a file that does not parse builds green through all six targets and fails
# only when quickshell starts — after a switch, on the machine, with no bar.
#
#   ./scripts/qml-check.sh            format + lint
#   ./scripts/qml-check.sh format     every .qml matches qmlformat
#   ./scripts/qml-check.sh lint       qmllint, against the built config
#   ./scripts/qml-check.sh probe      run the shell and open every popup
#
# Both tools come from the flake's own nixpkgs, never from PATH. A qmlformat
# from a different Qt reformats the whole tree, and a qmllint from a different
# Qt disagrees with the quickshell the shell actually runs under.

set -uo pipefail

cd "$(git rev-parse --show-toplevel)" || exit 2

QML_DIR=modules/quickshell/_qml

nl=$'\n'
export NIX_CONFIG="${NIX_CONFIG:+$NIX_CONFIG$nl}extra-experimental-features = nix-command flakes"

# Flakes only see tracked files.
git add -A >/dev/null 2>&1 || true

bad=0
fail() {
  echo "$1" >&2
  bad=1
}

pin() {
  nix build --no-link --print-out-paths --inputs-from . "nixpkgs#$1" 2>/dev/null
}

QTDECL=$(pin qt6.qtdeclarative)
QUICKSHELL=$(pin quickshell)
if [[ -z $QTDECL || -z $QUICKSHELL ]]; then
  echo "error: could not build qt6.qtdeclarative and quickshell from the pin" >&2
  exit 2
fi
QMLFORMAT=$QTDECL/bin/qmlformat
QMLLINT=$QTDECL/bin/qmllint

# The config derivation, not the source tree: Config.qml is generated, and the
# singleton every other file imports. Linting without it makes all 49 files
# report the same missing import. The host is measured, not written down.
config_attr() {
  nix eval --raw '.#homeConfigurations' --apply \
    'o: let ns = builtins.filter (n: (o.${n}.config.programs.quickshell.enable or false)) (builtins.attrNames o);
        in if ns == [] then "" else builtins.head ns' 2>/dev/null
}

build_config() {
  local who
  who=$(config_attr)
  [[ -n $who ]] || return 1
  nix build --no-link --print-out-paths \
    ".#homeConfigurations.\"$who\".config.programs.quickshell.configs.default" 2>/dev/null
}

CONFIG=$(build_config)
if [[ -z $CONFIG ]]; then
  echo "error: no homeConfiguration enables programs.quickshell" >&2
  exit 2
fi

# 1. Formatting. The tree is qmlformat-clean under default options and stays
#    that way, so a diff is a real deviation rather than a style opinion. Do
#    not add -n: it normalises attribute order and differs on every file.
check_format() {
  local n=0 f
  for f in $(find "$QML_DIR" -name '*.qml' | sort); do
    "$QMLFORMAT" "$f" 2>/dev/null | diff -q - "$f" >/dev/null ||
      { fail "$f: not qmlformat-clean; run  $QMLFORMAT -i $f"; n=$((n + 1)); }
  done
  # Config.qml has no source file to point at. It is generated by a `''` block
  # whose indentation is load-bearing — an interpolation that lands at column 0
  # reindents everything after it, which this catches and nothing else does.
  "$QMLFORMAT" "$CONFIG/Config.qml" 2>/dev/null | diff -q - "$CONFIG/Config.qml" >/dev/null ||
    { fail "modules/quickshell/_config.nix: the generated Config.qml is not qmlformat-clean"; n=$((n + 1)); }
  if [ $n -eq 0 ]; then echo "format: clean"; else echo "format: $n file(s) differ"; fi
}

# 2. Linting. quickshell synthesises a qmldir for the config directory at
#    runtime; qmllint will not, so build one per directory in a temp copy.
#    Nothing may be written into _qml/ — that tree ships wholesale into the
#    user's config, so a stray qmldir or .qmllint.ini moves the store path.
check_lint() {
  local tmp
  tmp=$(mktemp -d -t qml-check-XXXXXX) || return 2
  trap 'rm -rf "$tmp"' RETURN

  mkdir -p "$tmp/qs"
  cp -r --no-preserve=mode "$CONFIG/." "$tmp/qs/" || return 2

  local d rel mod f base
  while IFS= read -r d; do
    rel=${d#"$tmp"/qs}
    rel=${rel#/}
    mod=qs${rel:+.${rel//\//.}}
    {
      echo "module $mod"
      for f in "$d"/*.qml; do
        [ -e "$f" ] || continue
        base=$(basename "$f" .qml)
        # shell.qml is the entry point, not a type; QML types are capitalised.
        case $base in [a-z]*) continue ;; esac
        if head -1 "$f" | grep -q '^pragma Singleton'; then
          echo "singleton $base 1.0 $base.qml"
        else
          echo "$base 1.0 $base.qml"
        fi
      done
    } >"$d/qmldir"
  done < <(find "$tmp/qs" -type d | sort)

  # Four categories are off, all for one reason: quickshell's C++ types are
  # registered imperatively, so its .qmltypes describes them incompletely.
  # Each names the whole of what it currently suppresses, so a reader can tell
  # a tuned gate from an abandoned one. missing-property and unqualified are
  # NOT off — they are the two that catch a mistyped Config role or a name
  # resolved from the wrong scope — so their false positives are suppressed at
  # the two sites that have them instead.
  local off=(
    # PopupAnchor, DBusMenuHandle, UntypedObjectModel, Margins, QList<T*>.
    --unresolved-type disable
    # PanelWindow: quickshell constructs it from C++.
    --uncreatable-type disable
    # fallout from the unresolved PopupAnchor grouped property.
    --missing-type disable
    # QProcess::ExitStatus in Process.onExited.
    --signal-handler-parameters disable
  )

  local out
  out=$("$QMLLINT" "${off[@]}" \
    -I "$tmp" \
    -I "$QTDECL/lib/qt-6/qml" \
    -I "$QUICKSHELL/lib/qt-6/qml" \
    $(find "$tmp/qs" -name '*.qml' | sort) 2>&1)
  local rc=$?

  if [[ $rc -ne 0 || -n $out ]]; then
    # Point at the file a human edits, not at the temp copy.
    echo "$out" | sed "s#$tmp/qs/#$QML_DIR/#g" >&2
    fail "lint: qmllint rejected the shell's QML"
  else
    echo "lint: clean"
  fi
}

PROBE_SECONDS=${PROBE_SECONDS:-150}
PROBE_DIR=
PROBE_NOISE=
PROBE_HYPRLAND=

# 3. Running it. qmllint reads one file at a time and knows nothing about what
#    happens when the objects are built: a binding loop, a null dereference and
#    a popup that maps to no output all lint clean. quickshell has no --check,
#    so the only way to find those is to start the shell and open every popup.
#
#    Two properties make that safe to run next to the live shell. The session
#    gets a private bus, so Notifs cannot take org.freedesktop.Notifications
#    from the real one; and a private XDG_RUNTIME_DIR with the host's wayland,
#    pipewire and pulse sockets linked in, so `quickshell kill` and the Hyprland
#    IPC can only ever see the probe. Every ipc call is addressed by --pid on
#    top of that.
#
#    It is a nested compositor, so it needs a real one to display in: the
#    headless backend wants a KMS device for its allocator and there is none
#    without a seat. Inside a Hyprland session it is launched onto workspace 4
#    silently, so it never takes focus.
# Returns 0 clean, 1 the shell logged QML errors, 3 the nested session never
# came up. 3 is not a verdict on the QML: nesting a compositor in a live one
# fails occasionally, and a gate that reports a flake as a defect is worse than
# no gate.
probe_once() {
  local t placed host_wayland
  t=$(mktemp -d -t qml-probe-XXXXXX) || return 3
  PROBE_DIR=$t

  # The private runtime dir is the isolation. Only the sockets the shell has to
  # reach are linked in; everything it creates stays inside.
  mkdir -p "$t/run" && chmod 700 "$t/run"
  local sock
  for sock in pipewire-0 pipewire-0-manager pulse; do
    [ -e "$XDG_RUNTIME_DIR/$sock" ] && ln -sfn "$XDG_RUNTIME_DIR/$sock" "$t/run/$sock"
  done
  # The host's wayland socket is NOT linked in: the nested compositor would
  # then try to create its own under the same name and refuse to start. An
  # absolute WAYLAND_DISPLAY reaches the host directly, which leaves the
  # private dir free for the socket the probe creates.
  host_wayland=$WAYLAND_DISPLAY
  [[ $host_wayland == /* ]] || host_wayland=$XDG_RUNTIME_DIR/$WAYLAND_DISPLAY

  cat >"$t/driver.sh" <<EOF
#!/bin/sh
export PATH=$PROBE_HYPRLAND/bin:$QUICKSHELL/bin:\$PATH
quickshell -p "$CONFIG" --no-color >"$t/shell.log" 2>&1 &
qs=\$!
sleep 6
# a second output, so a popup that binds the wrong screen has somewhere wrong to go
hyprctl output create headless >/dev/null 2>&1
sleep 2
hyprctl monitors | grep -E '^Monitor ' >"$t/monitors"
for target in launcher clipboard switcher powermenu; do
  echo "== \$target" >>"$t/surfaces"
  quickshell ipc --pid \$qs call \$target toggle >>"$t/driver.log" 2>&1
  sleep 2
  hyprctl layers -j | grep -oE '"namespace": "[^"]*"' | sort | uniq -c >>"$t/surfaces"
  quickshell ipc --pid \$qs call \$target toggle >>"$t/driver.log" 2>&1
  sleep 1
done
quickshell ipc --pid \$qs call bar toggle >>"$t/driver.log" 2>&1
sleep 1
quickshell ipc --pid \$qs call bar toggle >>"$t/driver.log" 2>&1
sleep 1
kill \$qs 2>/dev/null
sleep 2
hyprctl dispatch exit
EOF

  cat >"$t/hypr.conf" <<EOF
monitor = ,preferred,auto,1
debug:disable_logs = 0
animations:enabled = 0
misc:disable_hyprland_logo = 1
misc:disable_splash_rendering = 1
misc:force_default_wallpaper = 0
exec-once = $t/driver.sh
EOF

  # The timeout is the outer bound: a compositor that hangs must still leave
  # the sentinel, or the caller waits for nothing.
  cat >"$t/session.sh" <<EOF
#!/bin/sh
timeout $((PROBE_SECONDS - 20)) env -u HYPRLAND_INSTANCE_SIGNATURE \
  XDG_RUNTIME_DIR="$t/run" WAYLAND_DISPLAY="$host_wayland" HYPRLAND_NO_CRASHREPORTER=1 \
  dbus-run-session -- $PROBE_HYPRLAND/bin/Hyprland --config "$t/hypr.conf" >"$t/hypr.log" 2>&1
touch "$t/done"
EOF
  chmod +x "$t/driver.sh" "$t/session.sh"

  # Placed on workspace 4 and silent, so the nested compositor's window never
  # takes focus. hyprctl's dispatch argument is Lua from 0.56 on; if that form
  # is rejected the probe still runs, it just lands on the current workspace.
  placed=
  if [[ -n ${HYPRLAND_INSTANCE_SIGNATURE:-} ]]; then
    placed=$("$PROBE_HYPRLAND/bin/hyprctl" dispatch \
      "hl.dsp.exec_cmd(\"[workspace 4 silent] $t/session.sh\")" 2>&1)
  fi
  if [[ $placed == ok ]]; then
    echo "probe: running on workspace 4 — silent, it will not take focus"
  else
    echo "probe: running in this session's current workspace"
    [[ -n $placed ]] && echo "  (hyprctl would not place it: ${placed%%$'\n'*})"
    "$t/session.sh" &
  fi

  local waited=0
  while [[ ! -e $t/done && $waited -lt $PROBE_SECONDS ]]; do
    sleep 2
    waited=$((waited + 2))
  done

  [[ -e $t/done ]] || return 3
  [[ -s $t/shell.log ]] || return 3

  # quickshell reports every QML runtime problem under the `scene` category —
  # TypeError, binding loops, failed assignments. Nothing else does, so the
  # whole gate is one grep. The two allowed lines are the nested session's own
  # artefacts, not the shell's: no portal and, when a socket is missing, no
  # pipewire.
  PROBE_NOISE=$(grep -vE 'qt\.qpa\.services: Failed to register with host portal|quickshell\.service\.pipewire' "$t/shell.log" |
    grep -E 'WARN scene:|ERROR')

  echo "probe: $(grep -c '^Monitor ' "$t/monitors" 2>/dev/null || echo 0) output(s), $(grep -c '^==' "$t/surfaces" 2>/dev/null || echo 0) popup(s) opened and closed"
  [[ -z $PROBE_NOISE ]]
}

check_probe() {
  PROBE_HYPRLAND=$(pin 'hyprland^out')
  if [[ -z $PROBE_HYPRLAND ]]; then
    echo "error: could not build hyprland from the pin" >&2
    return 2
  fi
  if [[ -z ${WAYLAND_DISPLAY:-} ]]; then
    echo "error: probe needs a wayland session to nest in" >&2
    return 2
  fi

  local attempt rc
  for attempt in 1 2; do
    PROBE_DIR= PROBE_NOISE=
    probe_once
    rc=$?
    [[ $rc -eq 3 ]] || break
    rm -rf "$PROBE_DIR"
    [[ $attempt -eq 1 ]] && echo "probe: the nested session did not come up; retrying once"
  done

  case $rc in
  0)
    echo "probe: clean"
    rm -rf "$PROBE_DIR"
    ;;
  3)
    fail "probe: the nested session did not come up twice; this is the harness, not the QML"
    ;;
  *)
    echo "$PROBE_NOISE" >&2
    fail "probe: the shell logged QML errors"
    echo "  full log: $PROBE_DIR/shell.log" >&2
    ;;
  esac
}


case ${1:-all} in
format) check_format ;;
lint) check_lint ;;
probe) check_probe ;;
all)
  check_format
  check_lint
  ;;
*)
  echo "usage: $0 [format|lint|probe]" >&2
  exit 2
  ;;
esac

exit $bad
