{
  lib,
  pkgs,
  config,
  ocr-copy,
}: let
  inherit (config.desktop) colors font;
  hasBar = config.dwl.bar;

  toBar = hex: "0x" + lib.toLower (lib.removePrefix "#" hex) + "ff";
  argvC = lib.concatMapStringsSep ", " (a: ''"${a}"'');
  cEsc = lib.replaceStrings [''\'' ''"''] [''\\'' ''\"''];

  menuArgvC = argvC config.launcher.argv;

  wpctl = "${pkgs.wireplumber}/bin/wpctl";
  brightnessctl = "${pkgs.brightnessctl}/bin/brightnessctl";
  playerctl = "${pkgs.playerctl}/bin/playerctl";

  # load-bearing: docs/decisions/sessions.md#dwl-column0
  barAppearance = lib.optionalString hasBar ''
    static const int showbar                   = 1;  /* 0 means no bar */
    static const int topbar                    = 1;  /* 0 means bottom bar */
    static const char *fonts[]                 = {"${font.name}:size=10"};
  '';

  colorTable =
    if hasBar
    then ''
      /* foreground, background, border */
      static uint32_t colors[][3] = {
        [SchemeNorm] = { ${toBar colors.base05}, ${toBar colors.base00}, ${toBar colors.base01} },
        [SchemeSel]  = { ${toBar colors.base05}, ${toBar colors.base02}, ${toBar colors.base03} },
        [SchemeUrg]  = { ${toBar colors.base00}, ${toBar colors.base08}, ${toBar colors.base08} },
      };''
    else ''
      /* base24 borders, same roles as the bar's colour table: unfocused sinks
         toward the background (base01), focused lifts a shade above it (base03). */
      static const float bordercolor[]           = COLOR(${toBar colors.base01});
      static const float focuscolor[]            = COLOR(${toBar colors.base03});
      static const float urgentcolor[]           = COLOR(${toBar colors.base08});'';

  tagging =
    if hasBar
    then ''static char *tags[] = { "1", "2", "3", "4", "5", "6", "7", "8", "9" };''
    else "#define TAGCOUNT (9) /* must be no greater than 31 */";

  toggleBarKey = lib.optionalString hasBar "  { MODKEY,                    XKB_KEY_b,      togglebar,        {0} },                /* super+b       -> toggle bar */";

  # load-bearing: docs/decisions/sessions.md#dwl-column0
  lockKey =
    lib.optionalString (config.lock.command != "")
    "  { MODKEY|WLR_MODIFIER_SHIFT, XKB_KEY_x, spawn, SHCMD(\"${cEsc config.lock.command}\") }, /* super+shift+x -> lock */";

  buttons =
    if hasBar
    then ''
      static const Button buttons[] = {
        { ClkLtSymbol, 0,      BTN_LEFT,   setlayout,      {.v = &layouts[0]} },
        { ClkLtSymbol, 0,      BTN_RIGHT,  setlayout,      {.v = &layouts[2]} },
        { ClkTitle,    0,      BTN_MIDDLE, zoom,           {0} },
        { ClkStatus,   0,      BTN_MIDDLE, spawn,          {.v = termcmd} },
        { ClkClient,   MODKEY, BTN_LEFT,   moveresize,     {.ui = CurMove} },
        { ClkClient,   MODKEY, BTN_MIDDLE, togglefloating, {0} },
        { ClkClient,   MODKEY, BTN_RIGHT,  moveresize,     {.ui = CurResize} },
        { ClkTagBar,   0,      BTN_LEFT,   view,           {0} },
        { ClkTagBar,   0,      BTN_RIGHT,  toggleview,     {0} },
        { ClkTagBar,   MODKEY, BTN_LEFT,   tag,            {0} },
        { ClkTagBar,   MODKEY, BTN_RIGHT,  toggletag,      {0} },
      };''
    else ''
      static const Button buttons[] = {
        { MODKEY, BTN_LEFT,   moveresize,     {.ui = CurMove} },
        { MODKEY, BTN_MIDDLE, togglefloating, {0} },
        { MODKEY, BTN_RIGHT,  moveresize,     {.ui = CurResize} },
      };'';
in ''
  /* Generated by home-manager (modules/dwl.nix) -- do not edit. */

  /* Taken from https://github.com/djpohly/dwl/issues/466 */
  #define COLOR(hex)    { ((hex >> 24) & 0xFF) / 255.0f, \
                          ((hex >> 16) & 0xFF) / 255.0f, \
                          ((hex >> 8) & 0xFF) / 255.0f, \
                          (hex & 0xFF) / 255.0f }

  /* appearance */
  static const int sloppyfocus               = 1;  /* focus follows mouse */
  static const int bypass_surface_visibility = 0;
  static const unsigned int borderpx         = 1;  /* border pixel of windows */
  ${barAppearance}static const float rootcolor[]             = COLOR(${toBar colors.base00});
  /* Set the alpha to zero to restore the old (pre xdg-protocol) behaviour. */
  static const float fullscreen_bg[]         = {0.0f, 0.0f, 0.0f, 1.0f};

  ${colorTable}

  /* tagging */
  ${tagging}

  /* logging */
  static int log_level = WLR_ERROR;

  static const Rule rules[] = {
    /* app_id  title  tags mask  isfloating  monitor */
    { NULL,    NULL,  0,         0,          -1 }, /* at least one rule must exist */
  };

  /* layout(s) */
  static const Layout layouts[] = {
    /* symbol  arrange function */
    { "[]=",   tile },
    { "><>",   NULL },    /* no layout function means floating behavior */
    { "[M]",   monocle },
  };

  /* monitors: runtime layout is applied by dwl-monitors (./display/monitors.nix) */
  static const MonitorRule monrules[] = {
    /* name  mfact  nmaster  scale  layout       rotate/reflect              x   y */
    { NULL,  0.55f, 1,       1,     &layouts[0], WL_OUTPUT_TRANSFORM_NORMAL, -1, -1 },
  };

  /* keyboard */
  static const struct xkb_rule_names xkb_rules = {
    .options = NULL,
  };

  static const int repeat_rate  = 25;
  static const int repeat_delay = 600;

  /* Trackpad */
  static const int tap_to_click            = 1;
  static const int tap_and_drag            = 1;
  static const int drag_lock               = 1;
  static const int natural_scrolling       = 0;
  static const int disable_while_typing    = 1;
  static const int left_handed             = 0;
  static const int middle_button_emulation = 0;
  static const enum libinput_config_scroll_method scroll_method = LIBINPUT_CONFIG_SCROLL_2FG;
  static const enum libinput_config_click_method click_method = LIBINPUT_CONFIG_CLICK_METHOD_BUTTON_AREAS;
  static const uint32_t send_events_mode = LIBINPUT_CONFIG_SEND_EVENTS_ENABLED;
  static const enum libinput_config_accel_profile accel_profile = LIBINPUT_CONFIG_ACCEL_PROFILE_ADAPTIVE;
  static const double accel_speed = 0.0;
  static const enum libinput_config_tap_button_map button_map = LIBINPUT_CONFIG_TAP_MAP_LRM;

  /* Use the Super/Windows key as the modifier (mirrors the hyprland session). */
  #define MODKEY WLR_MODIFIER_LOGO

  #define TAGKEYS(KEY,SKEY,TAG) \
    { MODKEY,                    KEY,  view,       {.ui = 1 << TAG} }, \
    { MODKEY|WLR_MODIFIER_CTRL,  KEY,  toggleview, {.ui = 1 << TAG} }, \
    { MODKEY|WLR_MODIFIER_SHIFT, SKEY, tag,        {.ui = 1 << TAG} }, \
    { MODKEY|WLR_MODIFIER_CTRL|WLR_MODIFIER_SHIFT, SKEY, toggletag, {.ui = 1 << TAG} }

  /* helper for spawning shell commands in the pre dwm-5.0 fashion */
  #define SHCMD(cmd) { .v = (const char*[]){ "/bin/sh", "-c", cmd, NULL } }

  /* commands: absolute store paths; termfbcmd is the terminal in the
     form that needs no running server */
  static const char *termcmd[]      = { ${argvC config.terminal.argv}, NULL };
  static const char *termfbcmd[]    = { ${argvC config.terminal.fallbackArgv}, NULL };
  static const char *menucmd[]      = { ${menuArgvC}, NULL };
  static const char *ocrcmd[]       = { "${ocr-copy}/bin/ocr-copy", NULL };
  static const char *volupcmd[]     = { "${wpctl}", "set-volume", "-l", "1", "@DEFAULT_AUDIO_SINK@", "5%+", NULL };
  static const char *voldncmd[]     = { "${wpctl}", "set-volume", "@DEFAULT_AUDIO_SINK@", "5%-", NULL };
  static const char *volmutecmd[]   = { "${wpctl}", "set-mute", "@DEFAULT_AUDIO_SINK@", "toggle", NULL };
  static const char *micmutecmd[]   = { "${wpctl}", "set-mute", "@DEFAULT_AUDIO_SOURCE@", "toggle", NULL };
  static const char *brightupcmd[]  = { "${brightnessctl}", "s", "10%+", NULL };
  static const char *brightdncmd[]  = { "${brightnessctl}", "s", "10%-", NULL };
  static const char *nextcmd[]      = { "${playerctl}", "next", NULL };
  static const char *prevcmd[]      = { "${playerctl}", "previous", NULL };
  static const char *playpausecmd[] = { "${playerctl}", "play-pause", NULL };

  static const Key keys[] = {
    /* --- applications & screenshots (mirror the hyprland binds) --- */
    { MODKEY,                    XKB_KEY_Return, spawn, {.v = termcmd} },   /* super+enter   -> terminal      */
    { MODKEY|WLR_MODIFIER_CTRL,  XKB_KEY_Return, spawn, {.v = termfbcmd} }, /* super+ctrl+enter -> terminal (server-down fallback) */
    { MODKEY,                    XKB_KEY_d,      spawn, {.v = menucmd} },   /* super+d       -> launcher      */
    { MODKEY,                    XKB_KEY_c,      spawn, {.v = ocrcmd} },    /* super+c       -> OCR to clip   */
    { MODKEY|WLR_MODIFIER_SHIFT, XKB_KEY_s,      spawn,                     /* super+shift+s -> shot (screen) */
      SHCMD("${cEsc config.screenshot.screen}") },
    { 0,                         XKB_KEY_Print,  spawn,                     /* print         -> shot (area)   */
      SHCMD("${cEsc config.screenshot.area}") },
    { MODKEY,                    XKB_KEY_v,      spawn,                     /* super+v       -> clipboard     */
      SHCMD("${cEsc config.clipboard.history}") },

    /* --- window & layout management --- */
    { MODKEY,                    XKB_KEY_q,      killclient,       {0} },                /* super+q       -> close      */
    { MODKEY,                    XKB_KEY_f,      togglefloating,   {0} },                /* super+f       -> float      */
    { MODKEY|WLR_MODIFIER_SHIFT, XKB_KEY_f,      togglefullscreen, {0} },                /* super+shift+f -> fullscreen */
  ${toggleBarKey}
    { MODKEY,                    XKB_KEY_j,      focusstack,       {.i = +1} },          /* super+j       -> focus next */
    { MODKEY,                    XKB_KEY_k,      focusstack,       {.i = -1} },          /* super+k       -> focus prev */
    { MODKEY,                    XKB_KEY_h,      setmfact,         {.f = -0.05f} },      /* super+h       -> shrink     */
    { MODKEY,                    XKB_KEY_l,      setmfact,         {.f = +0.05f} },      /* super+l       -> grow       */
    { MODKEY,                    XKB_KEY_i,      incnmaster,       {.i = +1} },          /* super+i       -> +master    */
    { MODKEY|WLR_MODIFIER_SHIFT, XKB_KEY_i,      incnmaster,       {.i = -1} },          /* super+shift+i -> -master    */
    { MODKEY|WLR_MODIFIER_SHIFT, XKB_KEY_Return, zoom,             {0} },                /* super+shift+enter -> zoom   */
    { MODKEY,                    XKB_KEY_t,      setlayout,        {.v = &layouts[0]} }, /* super+t       -> tile       */
    { MODKEY,                    XKB_KEY_m,      setlayout,        {.v = &layouts[2]} }, /* super+m       -> monocle    */
    { MODKEY,                    XKB_KEY_space,  setlayout,        {0} },                /* super+space   -> last layout */

    /* --- tags (hyprland workspaces 1-9): super+N view, super+shift+N move --- */
    { MODKEY,                    XKB_KEY_Tab,        view, {0} },        /* super+tab       -> last tag  */
    { MODKEY,                    XKB_KEY_0,          view, {.ui = ~0} }, /* super+0         -> all tags  */
    { MODKEY|WLR_MODIFIER_SHIFT, XKB_KEY_parenright, tag,  {.ui = ~0} }, /* super+shift+0   -> tag all   */
    TAGKEYS(XKB_KEY_1, XKB_KEY_exclam,      0),
    TAGKEYS(XKB_KEY_2, XKB_KEY_at,          1),
    TAGKEYS(XKB_KEY_3, XKB_KEY_numbersign,  2),
    TAGKEYS(XKB_KEY_4, XKB_KEY_dollar,      3),
    TAGKEYS(XKB_KEY_5, XKB_KEY_percent,     4),
    TAGKEYS(XKB_KEY_6, XKB_KEY_asciicircum, 5),
    TAGKEYS(XKB_KEY_7, XKB_KEY_ampersand,   6),
    TAGKEYS(XKB_KEY_8, XKB_KEY_asterisk,    7),
    TAGKEYS(XKB_KEY_9, XKB_KEY_parenleft,   8),

    /* --- multi-monitor (super+shift+h/l send the window across) --- */
    { MODKEY,                    XKB_KEY_comma,  focusmon, {.i = WLR_DIRECTION_LEFT} },
    { MODKEY,                    XKB_KEY_period, focusmon, {.i = WLR_DIRECTION_RIGHT} },
    { MODKEY|WLR_MODIFIER_SHIFT, XKB_KEY_h,      tagmon,   {.i = WLR_DIRECTION_LEFT} },
    { MODKEY|WLR_MODIFIER_SHIFT, XKB_KEY_l,      tagmon,   {.i = WLR_DIRECTION_RIGHT} },

    /* --- media, volume & brightness --- */
    { 0,      XKB_KEY_XF86AudioRaiseVolume, spawn, {.v = volupcmd} },
    { 0,      XKB_KEY_XF86AudioLowerVolume, spawn, {.v = voldncmd} },
    { 0,      XKB_KEY_XF86AudioMute,        spawn, {.v = volmutecmd} },
    { 0,      XKB_KEY_XF86AudioMicMute,     spawn, {.v = micmutecmd} },
    { MODKEY, XKB_KEY_bracketright,         spawn, {.v = brightupcmd} },
    { MODKEY, XKB_KEY_bracketleft,          spawn, {.v = brightdncmd} },
    { 0,      XKB_KEY_XF86AudioNext,        spawn, {.v = nextcmd} },
    { 0,      XKB_KEY_XF86AudioPrev,        spawn, {.v = prevcmd} },
    { 0,      XKB_KEY_XF86AudioPlay,        spawn, {.v = playpausecmd} },
    { 0,      XKB_KEY_XF86AudioPause,       spawn, {.v = playpausecmd} },

    /* --- lock, exit & VT switching --- */
  ${lockKey}
    { MODKEY|WLR_MODIFIER_SHIFT, XKB_KEY_z, quit, {0} }, /* super+shift+z -> exit dwl */
    { WLR_MODIFIER_CTRL|WLR_MODIFIER_ALT, XKB_KEY_Terminate_Server, quit, {0} },
  #define CHVT(n) { WLR_MODIFIER_CTRL|WLR_MODIFIER_ALT, XKB_KEY_XF86Switch_VT_##n, chvt, {.ui = (n)} }
    CHVT(1), CHVT(2), CHVT(3), CHVT(4),  CHVT(5),  CHVT(6),
    CHVT(7), CHVT(8), CHVT(9), CHVT(10), CHVT(11), CHVT(12),
  };

  ${buttons}
''
